Repository jenkins-x/jx-ui, pull requests merged in 2022-10, with the labels that each got.

#84 fix: change container port to 9200 for health check and remove args
  charts/jx-ui/templates/deployment.yaml
Labels: size/M, approved

#85 ci: add a step to build and lint helm charts
  .lighthouse/jenkins-x/pullrequest.yaml
  charts/jx-ui/templates/deployment.yaml
Labels: approved, size/XS

#87 fix: add sr to resource to list in values.yaml
  charts/jx-ui/values.yaml
Labels: approved, size/XS

#88 fix: add update to pr verbs
  charts/jx-ui/values.yaml
Labels: approved, size/XS

#91 Update adapter static 1.0.0 next.44
  web/package-lock.json
  web/package.json
Labels: approved, size/L
