Repository jenkins-x/jx-ui, pull requests merged in 2022-09, with the labels that each got.

#71 chore: Jenkins X build pack
  .golangci.yml
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  .lighthouse/jenkins-x/triggers.yaml
  Makefile
  OWNERS
  OWNERS_ALIASES
  charts/jx-ui/Chart.yaml
  charts/jx-ui/Makefile
  charts/jx-ui/templates/_helpers.tpl
  charts/jx-ui/templates/deployment.yaml
  charts/jx-ui/templates/ingress.yaml
  charts/jx-ui/templates/istio.yaml
  charts/jx-ui/templates/rbac.yaml
  charts/jx-ui/templates/service.yaml
  charts/jx-ui/values.yaml
Labels: size/XL, approved

#72 fix: add frontend build step to release pipeline
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/XS

#73 refactor: set CI=true for frontend build steps
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  hack/changelog-header.md
Labels: approved, size/S

#74 fix: new route /healthz
  internal/server/healthz.go
  internal/server/routes.go
Labels: approved, size/S

#76 refactor: upgrade sveltekit to 1.0.0-next.467
  OWNERS
  web/package-lock.json
  web/package.json
  web/src/routes/admin/+layout.js
  web/src/routes/admin/pipelines/[org]/[repo]/[branch]/[build]/+page.svelte
  web/svelte.config.js
Labels: approved, size/XXL

#75 feat: add modal to pipeline table
  internal/server/pipelines.go
  web/src/lib/cellRenderer.ts
  web/src/routes/admin/pipelines/+page.svelte
Labels: size/M, approved

#78 fix: override autoprefixer to remove color adjust warning
  web/package-lock.json
  web/package.json
Labels: approved, size/L

#80 fix: modal popup without clicking
  web/src/lib/cellRenderer.ts
Labels: approved, size/XS

#79 refactor: upgrade sveltekit to 1.0.0-next.497
  web/package-lock.json
  web/package.json
Labels: size/M, approved

#81 refactor: upgrade sveltekit to 1.0.0-next.502
  web/package-lock.json
  web/package.json
Labels: approved, size/S

#82 refactor: upgrade sveltekit to 1.0.0-next.503
  web/package-lock.json
  web/package.json
Labels: approved, size/S

#83 fix: dont bind to localhost
  internal/server/server.go
Labels: approved, size/XS
